/**
 * Quotes to display while AI is generating content
 * Inspired by movie references and sci-fi themes
 */
const AI_GENERATION_QUOTES = [
  'Contemplating the ifs.',
  'Checking all 14,000,605 outcomes.',
  'Consulting the oracle.',
  'Running the simulation.',
  'Calculating the odds.',
  'I like the look of these odds.',
  'This requires thought.',
  'Engaging analysis subroutine.',
  'Simulating a dream within a dream.',
  'Recalibrating the timeline.',
  'Plotting the course.',
  'Be cool.',
  'Now we play the waiting game.',
  'Aligning the probabilities.',
  'Searching for meaning.',
  'To infinity and beyond!',
  'If you build it, they will come.',
  'Don’t worry, be happy.',
  'Stay on target.',
  'Never tell me the odds.',
  'I have a good feeling about this.',
  'Do or do not. There is no try.',
  'Life finds a way.',
  'Patience, young grasshopper.',
  'Shall we play a game?',
  'The truth is out there.',
  'We are go for launch.',
  'Fasten your seatbelts.',
  'Let’s see what’s out there.',
  'Make it so.',
  'So say we all.',
  'Can’t stop the signal.',
  'Turn it up to 11.',
  'I love it when a plan comes together.',
  'Maximum effort.',
  'Higher, further, faster.',
  'Big things have small beginnings.',
  'The game’s afoot.',
  'Once more unto the breach.',
  'Down the rabbit hole.',
  'Curiouser and curiouser!',
  'Straight on till morning.',
  'Fortune favors the bold.',
  'Rome wasn’t built in a day.',
  'Slow and steady wins the race.',
  'The show must go on.',
  'Knowledge is power.',
  'Improvise. Adapt. Overcome.',
  'Time is an illusion.',
  'We are all born mad. Some remain so.',
  'Words are all we have.',
  'Life is habit. Or rather life is a succession of habits.',
  'Nothing happens, nobody comes, nobody goes, it’s awful.',
  'Ever tried. Ever failed. No matter. Try again. Fail again. Fail better.',
  'I can’t go on. I’ll go on.',
  'Nothing is more real than nothing.',
  'Try again. Fail again. Fail better.',
  'The struggle itself is enough to fill a man’s heart.',
  'In the midst of winter, I found there was, within me, an invincible summer.',
  'He who has a why to live can bear almost any how.',
  'Become who you are.',
  'That which does not kill us makes us stronger.',
  'To dare is to lose one’s footing momentarily. Not to dare is to lose oneself.',
  'Life can only be understood backwards; but it must be lived forwards.',
  'You have power over your mind — not outside events.',
  'What stands in the way becomes the way.',
  'Somewhere, something incredible is waiting to be known.',
  'We are a way for the universe to know itself.',
  'Those who can imagine anything, can create the impossible.',
  'It is good to have an end to journey toward; but it is the journey that matters.',
  'I have always imagined that Paradise will be a kind of library.',
  'Only those who will risk going too far can possibly find out how far one can go.',
  'A journey of a thousand miles begins with a single step.',
  'First say to yourself what you would be; and then do what you have to do.',
] as const

/**
 * Get a random quote from the AI generation quotes
 */
export function getRandomAIQuote(): string {
  const randomIndex = Math.floor(Math.random() * AI_GENERATION_QUOTES.length)
  return AI_GENERATION_QUOTES[randomIndex]!
}
