export const TEXT = {
  app: {
    name: 'kjopekraft.no',
  },
  common: {
    loading: '⏳ Laster...',
    loadingData: '⏳ Henter data…',
    loadingChart: '⏳ Bygger graf…',
    error: '🚨 Oops! Noe gikk galt.',
    noData: '— Ingen data tilgjengelig',
    save: '💾 Lagre',
    cancel: '❌ Avbryt',
    edit: 'Endre',
    remove: 'Fjern',
    add: '➕ Legg til',
    year: 'År',
    currency: 'NOK',
    reset: '🔄 Tilbakestill',
    confirmReset: '⚠️ Er du sikker på at du vil tilbakestille alle lønnspunkter?',
    confirmDelete: '⚠️ Er du sikker på at du vil slette dette lønnspunktet?',
    perYear: 'per år',
    lastTabPersistence: 'Du vil bli returnert til siste fanen du brukte ved neste besøk.',
    pts: 'kr',
    close: 'Lukk',
    legend: 'Forklaring',
    settings: 'Innstillinger',
  },
  aiValidator: {
    improveButton: 'Forbedre tekst',
    overlayTitle: 'Forslag til forbedring',
    overlayQuestionTitle: 'Forbedre argument',
    overlayQuestionHint: 'Svar kort for et bedre forslag.',
    overlaySuggestionTitle: 'Forslag klart',
    overlaySuggestionHint: 'Dette legges som nytt argument når du godtar.',
    originalLabel: 'Originaltekst',
    suggestionLabel: 'Forslag',
    editHint: 'Du kan redigere forslaget før du bruker det.',
    chatTitle: 'AI-oppfolging',
    chatInputPlaceholder: 'Skriv svaret ditt...',
    sendAnswer: 'Send svar',
    finishEarly: 'Avslutt og få forslag',
    showSuggestion: 'Vis hele',
    hideSuggestion: 'Skjul',
    applySuggestion: 'Bruk forslag',
    continueEditing: 'Fortsett å redigere',
    commitHint: 'Setter teksten i feltet. Trykk "Legg til argument" for å lagre.',
    inlineHint: 'AI-oppdatering klar. Rediger teksten og legg til argument.',
    aiSatisfied: 'AI er fornøyd med teksten.',
    retry: 'Prøv igjen',
    errorTitle: 'Klarte ikke å forbedre teksten.',
    emptyText: 'Skriv inn tekst før du forbedrer.',
    tooLong: (max: number) => `Teksten er for lang. Maks ${max} tegn.`,
  },

  // Mobile drawer
  drawer: {
    openDrawer: 'Åpne datapanel',
    closeDrawer: 'Lukk datapanel',
    dashboardTitle: 'Legg til lønnspunkt',
    negotiationTitle: 'Argumenter',
  },

  // Sidebar navigation
  sidebar: {
    brandName: 'Kjøpekraft',
    planLabel: '',
    navDashboard: 'Oversikt',
    navNegotiation: 'Forhandling',
    navHistory: 'Historikk',
    navReports: 'Rapporter',
    navSettings: 'Innstillinger',
    comingSoon: 'Kommer snart',
  },
  auth: {
    signIn: 'Logg inn',
    signOut: 'Logg ut',
    signInWithGoogle: 'Logg inn med Google',
    signInWithGithub: 'Logg inn med GitHub',
  },

  dashboard: {
    title: 'Har kjøpekraften din økt? 💸💸',
    noData: 'Legg til minst 2 lønnspunkter ➕ for å se grafen.',
    addPointsTitle: '➕ Legg til lønnspunkter',
    // New dashboard header text
    annualOverview: 'Lønnsoversikt',
    statusBanner: {
      purchasingPowerLabel: 'Kjøpekraft:',
      hideDetails: 'Skjul detaljer',
      showDetails: 'Vis detaljer',
      strongWin: {
        badge: 'Sterk vekst',
        headline: 'Du ligger foran inflasjonen',
        description: 'Kjøpekraften din har økt. Du har fått mer å rutte med.',
        cta: 'Se hva som har gjort forskjellen',
      },
      smallWin: {
        badge: 'Svak fremgang',
        headline: 'Du er så vidt foran – foreløpig',
        description: 'Lønnen din har økt litt mer enn prisene. Dette kan raskt endre seg.',
        cta: 'Sjekk forhandlingspotensialet ditt',
      },
      losing: {
        badge: 'Advarsel',
        headline: 'Du taper kjøpekraft',
        description: 'Prisene stiger raskere enn lønnen din. Du får mindre igjen for pengene.',
        cta: 'På tide å gjøre noe',
      },
      losingBadly: {
        badge: 'Kritisk',
        headline: 'Kjøpekraften din faller',
        description: 'Inflasjonen har tatt igjen inntekten din. Å stå stille betyr å gå bakover.',
        cta: 'Forbered neste lønnssamtale',
      },
      singlePoint: {
        badge: 'Trenger mer data',
        headline: 'Legg til minst ett lønnspunkt til',
        description: 'Vi trenger minst to lønnspunkter for å beregne endring i kjøpekraft.',
        cta: 'Legg til lønnspunkt',
      },
      singlePointNewJob: {
        badge: 'Ny jobb',
        headline: 'Bra start! Legg til forrige lønn',
        description:
          'Med én registrering ser vi ikke utviklingen ennå. Legg til lønnen før jobbskiftet.',
        cta: 'Legg til forrige lønn',
      },
      demoMode: {
        badge: 'Eksempeldata',
        headline: 'Du ser demo-data',
        description: 'Bytt til dine egne lønnspunkter for å få reelle innsikter.',
        cta: 'Bruk mine data',
      },
    },
    annualOverviewSubtitle: 'Følg lønnen din mot prisstigningen og se hva den faktisk er verdt',
    purchasingPowerDefinition:
      'Kjøpekraft viser hva lønnen din er verdt når vi tar høyde for prisstigningen.',
    fiscalYear: '{year}',
    addDataPrompt: 'Legg til lønnsdata for å se metrikker og grafer',
    noDataTitle: 'Ingen data å vise ennå',
    noDataSubtitle: 'Legg til lønnspunkter ved hjelp av skjemaet for å se vekstgrafen din',
    showNetSalary: 'Vis lønn etter skatt',
    showDataEntry: 'Legg til lønnspunkt',
    hideDataEntry: 'Skjul datapanel',
  },

  charts: {
    payDevelopmentTitle: '📊 Lønnsutvikling og prisstigning',
    xAxisLabel: 'År',
    yAxisLabel: 'Lønn (NOK)',
    actualPayLabel: 'Faktisk lønn',
    inflationAdjustedLabel: 'Lønn justert for prisstigning',
    inflationLabel: 'Inflasjon',
    yearPrefix: 'År: ',
    notAvailable: '—',
    minPointsRequired: 'Legg til minst to lønnspunkter for å vise graf.',
    showGross: 'Lønn før skatt',
    showNet: 'Lønn etter skatt',
    tabGuide:
      'Se hvordan lønnen din har utviklet seg sammenlignet med prisstigningen. Bruk denne grafen for å forstå kjøpekraften din over tid og forberede deg til lønnsforhandlinger.',
    // ChartSection header
    chartTitle: 'Årlig lønnsvekst og prisstigning',
    chartSubtitle: 'Følg lønnen din mot prisstigningen og se reell kjøpekraft.',
    // Mode toggle
    modeBadgeGross: 'FØR SKATT',
    modeBadgeNet: 'ETTER SKATT',
    modeToggleLabel: 'Vis lønn etter skatt',
    controlsLabel: 'Visningsalternativer',
    // Reference occupation
    compareWithOccupation: 'Sammenlign med et yrke',
    legendGross: 'Lønn før skatt',
    legendInflationAdjusted: 'Lønn justert for prisstigning',
    legendReference: 'Referanse',
    // Reference salary dropdown
    averageLabel: 'Gjennomsnitt',
    referenceHelp:
      'Referanselønn er snittet for valgt yrke. Bruk den for å se hvordan lønnen din ligger an.',
    noReference: 'Ingen referanse',
    referenceEnabled: 'Referanse aktiv',
  },

  settings: {
    displaySection: 'Visning',
    comparisonSection: 'Sammenligning',
    grossNetToggleTitle: 'Før / Etter skatt',
    grossNetToggleSubtitleGross: 'Vis nettolønn',
    grossNetToggleSubtitleNet: 'Vis bruttolønn',
    themeToggleTitle: 'Mørkt modus',
    themeToggleSubtitle: 'Bytt mellom lyst og mørkt tema',
    inflationBaseTitle: 'Inflasjonsbase',
    inflationBaseSubtitle: 'Velg året kjøpekraften regnes fra',
    inflationBaseAutoLabel: 'Automatisk (siste betydelige endring)',
    inflationBaseYearOption: (year: number, reasonLabel?: string) =>
      reasonLabel ? `${year} (${reasonLabel})` : String(year),
    inflationBaseInvalid: 'Bruk et år du har registrert, eller skriv "auto".',
    inflationBaseHint: 'Skriv "auto" eller et år du har data for.',
    occupationLabel: 'Yrke',
    occupationSearchPlaceholder: 'Søk etter yrkeskode eller tittel (SSB)',
    occupationNoResults: 'Ingen treff. Prøv en annen tittel eller kode.',
    selectedOccupationFallback: 'Valgt referanse',
    clearSelection: 'Fjern',
    occupationHelp: 'Sammenlign din lønnsutvikling med gjennomsnittet for et spesifikt yrke.',
  },

  views: {
    switcherLabel: 'Visning',
    graphLabel: 'Graf',
    tableLabel: 'Tabell',
    analysisLabel: 'Analyse',
    graphDescription: 'Visualiser lønnen din mot prisstigningen.',
    tableDescription: 'Se tallene med årlige endringer og referansegap.',
    analysisDescription: 'Høydepunkter fra lønnshistorikken din.',
    table: {
      columns: {
        year: 'År',
        date: 'Dato',
        event: 'Hendelse',
        salary: 'Lønn før skatt',
        netSalary: 'Lønn etter skatt',
        inflationAdjusted: 'Lønn justert for prisstigning',
        yoyChange: 'Endring mot forrige år',
        powerDelta: 'Kjøpekraft mot prisstigning',
        referenceGap: 'Avstand til referanse',
        progress: 'Langsiktig utvikling',
      },
      inflationVsPrev: 'Mot prisstigning (forrige år)',
      interpolated: 'Estimert',
      badgeGain: 'Over prisstigning',
      badgeLoss: 'Under prisstigning',
      noReference: 'Ingen referanse tilgjengelig for dette året',
      referenceOfficial: 'Offisiell',
      referenceEstimated: 'Estimert',
      referenceConfidence: {
        high: 'Høy datakvalitet',
        medium: 'Moderat datakvalitet',
        low: 'Begrenset datakvalitet',
      },
      eventDetailLabel: 'Årsak',
      purchasingPowerGain: 'Kjøpekraften økte',
      purchasingPowerLoss: 'Kjøpekraften falt',
      purchasingPowerFlat: 'Kjøpekraften var stabil',
      purchasingPowerDeltaLabel: 'Mot prisstigning',
      notAvailable: '—',
      longTermLabel: 'Karriereutvikling',
      longTermSince: (year: number) => `Siden ${year}`,
      expandDetails: 'Vis utvikling',
      collapseDetails: 'Skjul utvikling',
      firstYear: 'Første registrerte år',
      explanationTitle: 'Forklaring',
      primaryDriver: 'Hovedårsak',
      reasonNote: 'Notat',
      referenceTitle: 'Referansesammenligning',
      referenceLabel: 'Referanse',
      referencePosition: 'Din posisjon',
      referenceValue: 'Referanselønn',
      consistencyLabel: (wins: number, total: number) => `Reell vekst i ${wins} av ${total} år`,
    },
    analysis: {
      empty: 'Legg til flere lønnspunkter for å generere analyse.',
      largestRaiseTitle: 'Største lønnshopp',
      powerGainTitle: 'Høyeste kjøpekraft',
      powerLossTitle: 'Største fall i kjøpekraft',
      referenceWinsTitle: 'År over referanse',
      referenceLossesTitle: 'År under referanse',
      streakTitle: 'Sammenhengende år med lønn høyere enn prisstigningen',
      badgeRaise: 'Hopp',
      badgePower: 'Kraft',
      badgeHeadwind: 'Laveste kjøpekraft',
      badgeAhead: 'Over',
      badgeBehind: 'Under',
      badgeStreak: 'Rekke',
      yearsWon: 'år over referanse',
      yearsBehind: 'år under referanse',
      years: 'år',
    },
  },

  stats: {
    startingPay: 'Startlønn',
    latestPay: 'Nåværende lønn',
    inflationAdjustedPay: 'Lønn justert for prisstigning',
    gapPercent: 'Gap (%)',
  },

  // Metrics grid
  metrics: {
    totalAnnualSalary: 'Årslønn før skatt',
    totalAnnualNetSalary: 'Årslønn etter skatt',
    vsStart: 'mot start',
    realAnnualValue: 'Lønn justert for prisstigning',
    vsInflation: 'mot prisstigning',
    yearlyChange: 'Årlig endring',
    thisYear: 'i år',
  },

  forms: {
    yearLabel: 'År 📅',
    payLabel: 'Lønn (NOK) 💰',
    yearPlaceholder: 'f.eks. 2023',
    payPlaceholder: 'f.eks. 550 000',
    addPointButton: '➕ Legg til punkt',
    yourPoints: 'Dine lønnspunkter',
    noPointsMessage:
      'Ingen lønnspunkter lagt til ennå. Bruk skjemaet nedenfor for å komme i gang! 🚀',
    saveButton: '✅ Lagre',
    addButtonDisabledTitle: 'Fyll ut gyldige verdier før du legger til',
    addButtonTitle: 'Legg til nytt lønnspunkt',
    tabGuide:
      'Legg inn lønnspunktene dine for å få en oversikt over lønnsutviklingen. Jo flere punkter, jo bedre analyse får du!',
    validation: {
      yearRange: 'År må være mellom {min} og {max}',
      payPositive: 'Lønn må være større enn 0',
      required: 'Fyll ut alle felter',
      yearExists: 'Dette året er allerede lagt til',
      invalidInput: 'Ugyldig input',
      inflationDataUnavailable:
        'Inflasjonsdata er kun tilgjengelig fra {minYear}. Vennligst velg et senere år.',
    },
    // SalaryPointForm specific
    logSalaryPoint: 'Logg lønnspunkt',
    grossAmount: 'Beløp før skatt',
    netAmount: 'Beløp etter skatt',
    grossAmountHelp: 'Oppgi årlig bruttolønn i kroner (NOK).',
    netAmountHelp: 'Oppgi årlig nettolønn i kroner (NOK) etter skatt.',
    yearRange: 'År ({min}-{max})',
    saveLog: 'Lagre logg',
    reasonLabel: 'Hvorfor økte lønnen?',
    reasonPlaceholder: 'Velg årsak',
    reasonHelp: 'Brukes til å analysere lønnslinjer etter type endring.',
    reasonOptions: {
      adjustment: 'Ordinær justering',
      promotion: 'Forfremmelse',
      newJob: 'Ny jobb',
    },
    addNote: 'Legg til notat (valgfritt)',
    hideNote: 'Skjul notat',
    noteLabel: 'Notat',
    notePlaceholder: 'Kort beskrivelse (f.eks. “Forfremmet til senior”)',
    noteHelp: 'Notatet er kun for deg – vises sammen med detaljene for årslønnen.',
  },

  // Activity timeline
  activity: {
    recentActivity: 'Nylig aktivitet',
    noActivityYet: 'Ingen aktivitet ennå. Legg til ditt første lønnspunkt for å komme i gang!',
    salaryAdded: 'Lønn lagt til',
    thisYear: 'I år',
    lastYear: 'I fjor',
    yearsAgo: (years: number) => `${years} år siden`,
    reasons: {
      adjustment: 'Justering',
      promotion: 'Forfremmelse',
      newJob: 'Ny jobb',
    },
  },

  inflation: {
    title: '📈 Prisstigningsdata fra SSB',
    noDataTitle: 'Ingen prisstigningsdata',
    noDataMessage:
      'Kunne ikke laste prisstigningsdata fra SSB API. Bruker forhåndsdefinerte verdier.',
    latestData: 'Siste år: {year} med prisstigning på {inflation}% 🔥',
    showAllYears: 'Vis alle år ({count})',
    yearHeader: 'År',
    inflationHeader: 'Inflasjon (%)',
  },

  footer: {
    reportIssue: 'Rapporter problemer',
    license: 'Apache 2.0 lisens',
  },

  negotiationPage: {
    title: 'Lønnsforhandlings-assistent',
    subtitle: 'Bygg argumentene dine og generer et tydelig e-postutkast drevet av AI.',
    backToDashboard: 'Tilbake til oversikt',
  },

  negotiationForm: {
    detailsTitle: 'Detaljer',
    contextTitle: 'Kontekst',
    jobTitleLabel: 'Stillingstittel',
    jobTitlePlaceholder: 'F.eks. Utvikler, Prosjektleder',
    industryLabel: 'Bransje',
    industryPlaceholder: 'F.eks. IT, Helse, Bygg',
    isNewJobLabel: 'Ny jobb?',
    selectPlaceholder: 'Velg',
    yesOption: 'Ja',
    noOption: 'Nei',
    currentSalaryLabel: 'Nåværende lønnsnivå',
    currentSalaryPlaceholder: 'F.eks. 650 000 kr',
    desiredSalaryLabel: 'Ønsket lønnsnivå',
    desiredSalaryPlaceholder: 'F.eks. 700 000 kr',
    marketDataLabel: 'Markedsdata/lønnsstatistikk',
    marketDataPlaceholder: 'F.eks. SSB: Medianlønn for din rolle, rapporter, etc.',
    marketDataHint:
      'SSB-data hentes automatisk når stillingstittel er oppgitt. Du kan legge til egne kilder hvis vi ikke finner en match.',
    otherBenefitsLabel: 'Betingelser/goder',
    otherBenefitsPlaceholder: 'F.eks. bonus, ekstra ferie, fleksibilitet',
    achievementsNote: 'Prestasjoner/resultater legges til som egne forhandlingspunkter nedenfor.',
  },

  negotiation: {
    sectionTitle: 'Forhandling',
    argumentBuilderTitle: 'Argumentbygger',
    argumentsTitle: 'Dine argumenter',
    addArgument: 'Legg til argument',
    showArguments: 'Vis argumenter',
    hideArguments: 'Skjul argumenter',
    guide:
      'Legg inn dine viktigste argumenter for lønnsforhandling. Skriv fritt og bruk flere punkter – dette hjelper deg å forberede en god forhandlingsstrategi!',
    descriptionPlaceholder: 'Beskriv et argument, prestasjon eller markedssituasjon',
    keyPointPlaceholder: 'Beskriv nøkkelpunktet ditt...',
    typePlaceholder: 'Velg type',
    typeAchievement: 'Prestasjon',
    typeMarket: 'Marked',
    typeResponsibility: 'Ansvar',
    typeCompetence: 'Kompetanse',
    typeOther: 'Annet',
    addButton: 'Legg til',
    addToList: 'Legg til i listen',
    emailButton: 'Generer forslag',
    playbookButton: 'Spillbok',
    generating: 'Genererer...',
    remaining: 'igjen',
    generateEmail: 'Generer forslag',
    generatePlaybook: 'Generer spillbok',
    generatingEmail: 'Genererer e-post...',
    generatingPlaybook: 'Genererer spillbok...',
    tabGuide:
      'Legg inn dine viktigste argumenter og generer et forslag til e-post. Dette hjelper deg å være best mulig forberedt!',
    minPointsWarning: 'Legg til minst ett forhandlingspunkt før du genererer innhold.',
    suggestionMorePoints: 'Tips: Legg til flere punkter for bedre resultater (anbefalt: 3+)',
    addPointsHint: 'Legg til dine nøkkelpunkter ovenfor',
    maxPointsWarning: 'Du har nådd maks antall forhandlingspunkter.',
    maxGenerationsWarning: 'Du har nådd maks antall genereringer.',
    emailErrorTitle: 'Det oppstod en feil med e-post generering',
    playbookErrorTitle: 'Det oppstod en feil med spillbok generering',
    copyMarkdown: 'Kopier markdown',
    copyMarkdownSuccess: 'Markdown kopiert!',
    copyMarkdownError: 'Kunne ikke kopiere markdown',
    copyRich: 'Kopier som rik tekst',
    copyRichSuccess: 'Rik tekst kopiert!',
    copyRichError: 'Kunne ikke kopiere rik tekst',
    downloadDocx: 'Last ned som DOCX',
    collapseEmail: 'Vis/skjul e-post',
    collapsePlaybook: 'Vis/skjul spillbok',
    emailSectionTitle: 'Forslag til e-post',
    playbookSectionTitle: 'Spillbok',
    copyPrompt: 'Kopier prompt',
    noPointsYet: 'Ingen punkter lagt til ennå',
    yourPoints: 'Dine forhandlingspunkter',
    removePoint: 'Fjern punkt',
    // SSB data notices for AI-generated content
    ssbDataNotices: {
      approximateMatch: 'Merk: Bruker nærmeste yrkeskategori ({occupation}) fra SSB',
      noDataAvailable: 'Kunne ikke finne relevant SSB-data for dette yrket',
      dataSourceCitation: 'Kilde: SSB Tabell 11418',
      usingEstimate: 'Bruker estimert data for {year}',
      occupationCodes: {
        '2223': 'Sykepleiere',
        '2512': 'Programvareutviklere',
        '2330': 'Lærere',
        '2146': 'Ingeniører (bygg og anlegg)',
      },
    },
  },

  negotiationSummary: {
    title: 'Forhandlingsoppsummering',
    subtitle: 'Basert på lønnsdata, inflasjon og SSB-markedstall.',
    badge: 'SSB + inflasjon',
    inflationLabel: 'Kjøpekraft',
    marketLabel: 'Marked',
    raiseLabel: 'Anbefalt spenn',
    aboveInflation: (percent: string) => `Du ligger ${percent} over inflasjonen.`,
    belowInflation: (percent: string) => `Du ligger ${percent} under inflasjonen.`,
    noInflationData: 'Legg inn lønnsdata i oversikten for å se kjøpekraften din.',
    marketMedian: (occupation: string, year: number, value: string) =>
      `Medianlønn for ${occupation} (${year}): ${value}.`,
    loadingMarketData: 'Henter markedsdata fra SSB...',
    marketDataError: 'Kunne ikke hente markedsdata fra SSB akkurat nå.',
    noMarketData: 'Fant ingen SSB-match. Legg til egne markedsdata om du vil.',
    desiredAboveMedian: (percent: string) => `Ønsket lønn er ${percent} over medianen.`,
    desiredBelowMedian: (percent: string) => `Ønsket lønn er ${percent} under medianen.`,
    desiredAtMedian: 'Ønsket lønn er på medianen.',
    noDesiredComparison: 'Legg inn ønsket lønn for å sammenligne med markedet.',
    suggestedRange: (min: string, max: string) => `${min}–${max}`,
    approximateMatch: (occupation: string) =>
      `Merk: Bruker nærmeste yrkeskategori (${occupation}).`,
    footer: 'Tips: Bruk tallene som støtte, men tilpass ønsket til din situasjon.',
  },

  negotiationSuggestions: {
    title: 'Forslag til argumenter',
    subtitle: 'Velg punkter som passer deg, og rediger dem videre i argumentbyggeren.',
    addLabel: 'Legg til',
    addedLabel: 'Lagt til',
    items: {
      responsibility: 'Jeg har tatt på meg nye ansvarsområder utover stillingsbeskrivelsen.',
      results: 'Jeg har levert resultater som har gitt målbar verdi eller spart kostnader.',
      skills: 'Jeg har utviklet ny kompetanse eller sertifiseringer som styrker rollen min.',
      loyalty: 'Jeg har vært stabil over tid og bidrar med kontinuitet og trygghet.',
      projects: 'Jeg har levert krevende prosjekter og støttet viktige kunde- eller teambehov.',
      growth: 'Jeg utvikler meg faglig og kan ta større ansvar fremover.',
    },
  },

  negotiationBenefits: {
    title: 'Forhandle goder',
    description:
      'Velg goder som er viktige for deg. Hvis lønnen ikke møter ønsket nivå, kan goder være et godt alternativ.',
    toggleLabel: 'Vis alle goder',
    notesLabel: 'Andre goder (valgfritt)',
    notesPlaceholder: 'F.eks. fleksibel oppstart, ekstra ferieuke, helseforsikring',
    items: {
      pension: 'Pensjon',
      bonus: 'Bonus',
      equity: 'Aksjer/opsjoner',
      extraVacation: 'Ekstra ferie',
      flexTime: 'Fleksitid',
      remoteWork: 'Hjemmekontor/fjernarbeid',
      insurance: 'Forsikringer',
      training: 'Kompetansebudsjett/sertifiseringer',
      wellness: 'Helse/velværetiltak',
      phoneInternet: 'Mobil/bredbånd',
      overtime: 'Overtidsavtale',
      travel: 'Reisegodtgjørelse',
    },
  },

  onboarding: {
    welcomeTitle: 'Velkommen til Kjøpekraft',
    welcomeMessage:
      'Få oversikt over hva lønnen din er verdt etter prisstigningen. Sammenlign lønnsutviklingen din med prisstigningen for å se den reelle kjøpekraften.',
    primaryCta: 'Kom i gang',
    loadDemoButton: 'Prøv med eksempeldata',
    addOwnDataButton: 'Legg til min egen lønn',
    loadDemoLink: 'Prøv med eksempeldata',
    addOwnDataLink: 'Legg til min egen lønn',
    whatIsKjopekraft: 'Hva er kjøpekraft?',
    kjopekraftExplanation:
      'Kjøpekraft viser hva lønnen din er verdt når prisene øker. Selv om lønnen din øker med 10 %, kan prisstigningen spise opp mye av veksten. Vi viser forskjellen mellom lønn på papiret og hva du faktisk kan kjøpe.',
    features: {
      trackSalary: {
        title: 'Spor lønnsutvikling',
        description: 'Se hvordan lønnen din endrer seg over tid.',
      },
      compareInflation: {
        title: 'Sammenlign med prisstigning',
        description: 'Forstå kjøpekraften din, ikke bare tallene.',
      },
      negotiate: {
        title: 'Forhandle smartere',
        description: 'Få innsikt som støtter lønnsforhandlinger.',
      },
    },
    demoDataTitle: 'Du ser eksempeldata',
    demoDataInfo:
      'Dette er eksempeldata. Legg til dine egne lønnspunkter for å se din faktiske utvikling.',
    demoDataCta: 'Bruk mine data',
    clearDemoData: 'Fjern eksempeldata',
  },

  help: {
    realAnnualValue:
      'Dette viser hva startlønnen din ville vært verdt i dag, justert for prisstigning. Sammenligner kjøpekraften din nå mot da.',
    inflationAdjusted:
      'Viser hvordan lønnen din ville utviklet seg hvis den hadde fulgt prisstigningen fra starttidspunktet. Hjelper deg se om du har fått reell lønnsvekst.',
    yearlyChange:
      'Den prosentvise endringen i lønnen din fra start til nå, korrigert for prisstigning. Viser om kjøpekraften din har økt eller sunket.',
  },

  referenceSalary: {
    toggleLabel: 'Sammenlign med referanselønn',
    chartLabel: 'Referanse (Sykepleiere)',
    occupation: 'Sykepleiere',
    sourceLabel: 'Kilde: SSB',
    description: 'Median årslønn for sykepleiere (SSB)',
    enabledBadge: 'Referanse aktiv',
    helpText:
      'Sammenlign din lønnsutvikling med gjennomsnittslønn for sykepleiere i Norge basert på SSB data.',
    estimated: 'Estimert',
    official: 'Offisiell',
    estimatedNote: 'Estimert basert på SSB lønnsindeks',
  },
}
