export const TEXT = {
  common: {
    loading: '⏳ Laster...',
    loadingData: '⏳ Henter data…',
    loadingChart: '⏳ Bygger graf…',
    error: '🚨 Oops! Noe gikk galt.',
    noData: '— Ingen data tilgjengelig',
    save: '💾 Lagre',
    cancel: '❌ Avbryt',
    edit: 'Endre',
    remove: 'Fjern',
    add: '➕ Legg til',
    year: 'År',
    currency: 'NOK',
    reset: '🔄 Tilbakestill',
    confirmReset: '⚠️ Er du sikker på at du vil tilbakestille alle lønnspunkter?',
    confirmDelete: '⚠️ Er du sikker på at du vil slette dette lønnspunktet?',
    perYear: 'per år',
    lastTabPersistence: 'Du vil bli returnert til siste fanen du brukte ved neste besøk.',
    pts: 'kr',
    close: 'Lukk',
    legend: 'Forklaring',
    settings: 'Innstillinger',
  },

  // Mobile drawer
  drawer: {
    openDrawer: 'Åpne datapanel',
    closeDrawer: 'Lukk datapanel',
    dashboardTitle: 'Legg til lønnspunkt',
    negotiationTitle: 'Argumenter',
  },

  // Sidebar navigation
  sidebar: {
    brandName: 'Kjøpekraft',
    planLabel: '',
    navDashboard: 'Oversikt',
    navNegotiation: 'Forhandling',
    navHistory: 'Historikk',
    navReports: 'Rapporter',
    navSettings: 'Innstillinger',
    comingSoon: 'Kommer snart',
  },

  dashboard: {
    title: 'Har kjøpekraften din økt? 💸💸',
    noData: 'Legg til minst 2 lønnspunkter ➕ for å se grafen.',
    addPointsTitle: '➕ Legg til lønnspunkter',
    // New dashboard header text
    annualOverview: 'Lønnsoversikt',
    annualOverviewSubtitle: 'Følg lønnen din mot prisstigningen og se hva den faktisk er verdt',
    purchasingPowerDefinition:
      'Kjøpekraft viser hva lønnen din er verdt når vi tar høyde for prisstigningen.',
    fiscalYear: '{year}',
    addDataPrompt: 'Legg til lønnsdata for å se metrikker og grafer',
    noDataTitle: 'Ingen data å vise ennå',
    noDataSubtitle: 'Legg til lønnspunkter ved hjelp av skjemaet for å se vekstgrafen din',
    showNetSalary: 'Vis lønn etter skatt',
    showDataEntry: 'Legg til lønnspunkt',
    hideDataEntry: 'Skjul datapanel',
  },

  charts: {
    payDevelopmentTitle: '📊 Lønnsutvikling og prisstigning',
    xAxisLabel: 'År',
    yAxisLabel: 'Lønn (NOK)',
    actualPayLabel: 'Faktisk lønn',
    inflationAdjustedLabel: 'Lønn justert for prisstigning',
    inflationLabel: 'Inflasjon',
    yearPrefix: 'År: ',
    notAvailable: '—',
    minPointsRequired: 'Legg til minst to lønnspunkter for å vise graf.',
    showGross: 'Lønn før skatt',
    showNet: 'Lønn etter skatt',
    tabGuide:
      'Se hvordan lønnen din har utviklet seg sammenlignet med prisstigningen. Bruk denne grafen for å forstå kjøpekraften din over tid og forberede deg til lønnsforhandlinger.',
    // ChartSection header
    chartTitle: 'Årlig lønnsvekst og prisstigning',
    chartSubtitle: 'Følg lønnen din mot prisstigningen og se reell kjøpekraft.',
    // Mode toggle
    modeBadgeGross: 'FØR SKATT',
    modeBadgeNet: 'ETTER SKATT',
    modeToggleLabel: 'Vis lønn etter skatt',
    controlsLabel: 'Visningsalternativer',
    // Reference occupation
    compareWithOccupation: 'Sammenlign med et yrke',
    legendGross: 'Lønn før skatt',
    legendInflationAdjusted: 'Lønn justert for prisstigning',
    legendReference: 'Referanse',
    // Reference salary dropdown
    averageLabel: 'Gjennomsnitt',
    referenceHelp:
      'Referanselønn er snittet for valgt yrke. Bruk den for å se hvordan lønnen din ligger an.',
    noReference: 'Ingen referanse',
    // Event baselines toggle
    showEventBaselines: 'Vis hendelseslinjer',
    referenceEnabled: 'Referanse aktiv',
    eventBaselinesHelp: 'Vis linjer som markerer prisstigning fra forfremmelser og jobbskift',
  },

  views: {
    switcherLabel: 'Visning',
    graphLabel: 'Graf',
    tableLabel: 'Tabell',
    analysisLabel: 'Analyse',
    graphDescription: 'Visualiser lønnen din mot prisstigningen.',
    tableDescription: 'Se tallene med årlige endringer og referansegap.',
    analysisDescription: 'Høydepunkter fra lønnshistorikken din.',
    table: {
      columns: {
        year: 'År',
        date: 'Dato',
        event: 'Hendelse',
        salary: 'Lønn før skatt',
        netSalary: 'Lønn etter skatt',
        inflationAdjusted: 'Lønn justert for prisstigning',
        yoyChange: 'Endring mot forrige år',
        powerDelta: 'Kjøpekraft mot prisstigning',
        referenceGap: 'Avstand til referanse',
        progress: 'Langsiktig utvikling',
      },
      inflationVsPrev: 'Mot prisstigning (forrige år)',
      interpolated: 'Estimert',
      badgeGain: 'Over prisstigning',
      badgeLoss: 'Under prisstigning',
      noReference: 'Ingen referanse tilgjengelig for dette året',
      referenceOfficial: 'Offisiell',
      referenceEstimated: 'Estimert',
      referenceConfidence: {
        high: 'Høy datakvalitet',
        medium: 'Moderat datakvalitet',
        low: 'Begrenset datakvalitet',
      },
      eventDetailLabel: 'Årsak',
      purchasingPowerGain: 'Kjøpekraften økte',
      purchasingPowerLoss: 'Kjøpekraften falt',
      purchasingPowerFlat: 'Kjøpekraften var stabil',
      purchasingPowerDeltaLabel: 'Mot prisstigning',
      longTermLabel: 'Karriereutvikling',
      longTermSince: (year: number) => `Siden ${year}`,
      expandDetails: 'Vis utvikling',
      collapseDetails: 'Skjul utvikling',
      firstYear: 'Første registrerte år',
      explanationTitle: 'Forklaring',
      primaryDriver: 'Hovedårsak',
      reasonNote: 'Notat',
      referenceTitle: 'Referansesammenligning',
      referenceLabel: 'Referanse',
      referencePosition: 'Din posisjon',
      referenceValue: 'Referanselønn',
      consistencyLabel: (wins: number, total: number) => `Reell vekst i ${wins} av ${total} år`,
    },
    analysis: {
      empty: 'Legg til flere lønnspunkter for å generere analyse.',
      largestRaiseTitle: 'Største lønnshopp',
      powerGainTitle: 'Høyeste kjøpekraft',
      powerLossTitle: 'Største fall i kjøpekraft',
      referenceWinsTitle: 'År over referanse',
      referenceLossesTitle: 'År under referanse',
      streakTitle: 'Sammenhengende år med lønn høyere enn prisstigningen',
      badgeRaise: 'Hopp',
      badgePower: 'Kraft',
      badgeHeadwind: 'Laveste kjøpekraft',
      badgeAhead: 'Over',
      badgeBehind: 'Under',
      badgeStreak: 'Rekke',
      yearsWon: 'år over referanse',
      yearsBehind: 'år under referanse',
      years: 'år',
    },
  },

  stats: {
    startingPay: 'Startlønn',
    latestPay: 'Nåværende lønn',
    inflationAdjustedPay: 'Lønn justert for prisstigning',
    gapPercent: 'Gap (%)',
  },

  // Metrics grid
  metrics: {
    totalAnnualSalary: 'Årslønn før skatt',
    totalAnnualNetSalary: 'Årslønn etter skatt',
    vsStart: 'mot start',
    realAnnualValue: 'Lønn justert for prisstigning',
    vsInflation: 'mot prisstigning',
    yearlyChange: 'Årlig endring',
    thisYear: 'i år',
  },

  forms: {
    yearLabel: 'År 📅',
    payLabel: 'Lønn (NOK) 💰',
    yearPlaceholder: 'f.eks. 2023',
    payPlaceholder: 'f.eks. 550 000',
    addPointButton: '➕ Legg til punkt',
    yourPoints: 'Dine lønnspunkter',
    noPointsMessage:
      'Ingen lønnspunkter lagt til ennå. Bruk skjemaet nedenfor for å komme i gang! 🚀',
    saveButton: '✅ Lagre',
    addButtonDisabledTitle: 'Fyll ut gyldige verdier før du legger til',
    addButtonTitle: 'Legg til nytt lønnspunkt',
    tabGuide:
      'Legg inn lønnspunktene dine for å få en oversikt over lønnsutviklingen. Jo flere punkter, jo bedre analyse får du!',
    validation: {
      yearRange: 'År må være mellom {min} og {max}',
      payPositive: 'Lønn må være større enn 0',
      required: 'Fyll ut alle felter',
      yearExists: 'Dette året er allerede lagt til',
      invalidInput: 'Ugyldig input',
      inflationDataUnavailable:
        'Inflasjonsdata er kun tilgjengelig fra {minYear}. Vennligst velg et senere år.',
    },
    // SalaryPointForm specific
    logSalaryPoint: 'Logg lønnspunkt',
    grossAmount: 'Beløp før skatt',
    netAmount: 'Beløp etter skatt',
    grossAmountHelp: 'Oppgi årlig bruttolønn i kroner (NOK).',
    netAmountHelp: 'Oppgi årlig nettolønn i kroner (NOK) etter skatt.',
    yearRange: 'År ({min}-{max})',
    saveLog: 'Lagre logg',
    reasonLabel: 'Hvorfor økte lønnen?',
    reasonPlaceholder: 'Velg årsak',
    reasonHelp: 'Brukes til å analysere lønnslinjer etter type endring.',
    reasonOptions: {
      adjustment: 'Ordinær justering',
      promotion: 'Forfremmelse',
      newJob: 'Ny jobb',
    },
    addNote: 'Legg til notat (valgfritt)',
    hideNote: 'Skjul notat',
    noteLabel: 'Notat',
    notePlaceholder: 'Kort beskrivelse (f.eks. “Forfremmet til senior”)',
    noteHelp: 'Notatet er kun for deg – vises sammen med detaljene for årslønnen.',
  },

  // Activity timeline
  activity: {
    recentActivity: 'Nylig aktivitet',
    noActivityYet: 'Ingen aktivitet ennå. Legg til ditt første lønnspunkt for å komme i gang!',
    salaryAdded: 'Lønn lagt til',
    thisYear: 'I år',
    lastYear: 'I fjor',
    yearsAgo: (years: number) => `${years} år siden`,
    reasons: {
      adjustment: 'Justering',
      promotion: 'Forfremmelse',
      newJob: 'Ny jobb',
    },
  },

  inflation: {
    title: '📈 Prisstigningsdata fra SSB',
    noDataTitle: 'Ingen prisstigningsdata',
    noDataMessage:
      'Kunne ikke laste prisstigningsdata fra SSB API. Bruker forhåndsdefinerte verdier.',
    latestData: 'Siste år: {year} med prisstigning på {inflation}% 🔥',
    showAllYears: 'Vis alle år ({count})',
    yearHeader: 'År',
    inflationHeader: 'Inflasjon (%)',
  },

  footer: {
    reportIssue: 'Rapporter problemer',
    license: 'Apache 2.0 lisens',
  },

  negotiationPage: {
    title: 'Lønnsforhandlings-assistent',
    subtitle: 'Generer personlige forhandlingsstrategier og e-poster drevet av AI.',
    backToDashboard: 'Tilbake til oversikt',
  },

  negotiationForm: {
    detailsTitle: 'Detaljer',
    contextTitle: 'Kontekst',
    jobTitleLabel: 'Stillingstittel',
    jobTitlePlaceholder: 'F.eks. Utvikler, Prosjektleder',
    industryLabel: 'Bransje',
    industryPlaceholder: 'F.eks. IT, Helse, Bygg',
    isNewJobLabel: 'Ny jobb?',
    selectPlaceholder: 'Velg',
    yesOption: 'Ja',
    noOption: 'Nei',
    currentSalaryLabel: 'Nåværende lønnsnivå',
    currentSalaryPlaceholder: 'F.eks. 650 000 kr',
    desiredSalaryLabel: 'Ønsket lønnsnivå',
    desiredSalaryPlaceholder: 'F.eks. 700 000 kr',
    marketDataLabel: 'Markedsdata/lønnsstatistikk',
    marketDataPlaceholder: 'F.eks. SSB: Medianlønn for din rolle, rapporter, etc.',
    otherBenefitsLabel: 'Betingelser/goder',
    otherBenefitsPlaceholder: 'F.eks. bonus, ekstra ferie, fleksibilitet',
    achievementsNote: 'Prestasjoner/resultater legges til som egne forhandlingspunkter nedenfor.',
  },

  negotiation: {
    sectionTitle: 'Forhandling',
    argumentBuilderTitle: 'Argumentbygger',
    showArguments: 'Vis argumenter',
    hideArguments: 'Skjul argumenter',
    guide:
      'Legg inn dine viktigste argumenter for lønnsforhandling. Skriv fritt og bruk flere punkter – dette hjelper deg å forberede en god forhandlingsstrategi! Du kan også generere en e-post eller et forhandlings-playbook basert på punktene dine.',
    descriptionPlaceholder: 'Beskriv et argument, prestasjon eller markedssituasjon',
    keyPointPlaceholder: 'Beskriv nøkkelpunktet ditt...',
    typePlaceholder: 'Velg type',
    typeAchievement: 'Prestasjon',
    typeExperience: 'Erfaring',
    typeMarket: 'Marked',
    typeResponsibility: 'Ansvar',
    typeCertification: 'Sertifisering',
    addButton: 'Legg til',
    addToList: 'Legg til i listen',
    emailButton: 'E-post',
    playbookButton: 'Spillbok',
    generating: 'Genererer...',
    remaining: 'igjen',
    generateEmail: 'Generer e-post',
    generatePlaybook: 'Generer spillbok',
    generatingEmail: 'Genererer e-post...',
    generatingPlaybook: 'Genererer spillbok...',
    tabGuide:
      'Legg inn dine viktigste argumenter og generer e-post eller spillbok for forhandling. Dette hjelper deg å være best mulig forberedt!',
    minPointsWarning: 'Legg til minst ett forhandlingspunkt før du genererer innhold.',
    suggestionMorePoints: 'Tips: Legg til flere punkter for bedre resultater (anbefalt: 3+)',
    addPointsHint: 'Legg til dine nøkkelpunkter ovenfor',
    maxGenerationsWarning: 'Du har nådd maks antall genereringer.',
    emailErrorTitle: 'Det oppstod en feil med e-post generering',
    playbookErrorTitle: 'Det oppstod en feil med spillbok generering',
    copyMarkdown: 'Kopier markdown',
    copyMarkdownSuccess: 'Markdown kopiert!',
    copyMarkdownError: 'Kunne ikke kopiere markdown',
    copyRich: 'Kopier som rik tekst',
    copyRichSuccess: 'Rik tekst kopiert!',
    copyRichError: 'Kunne ikke kopiere rik tekst',
    downloadDocx: 'Last ned som DOCX',
    collapseEmail: 'Vis/skjul e-post',
    collapsePlaybook: 'Vis/skjul spillbok',
    emailSectionTitle: 'Forslag til e-post',
    playbookSectionTitle: 'Spillbok',
    copyPrompt: 'Kopier prompt',
    noPointsYet: 'Ingen punkter lagt til ennå',
    yourPoints: 'Dine forhandlingspunkter',
    removePoint: 'Fjern punkt',
    // SSB data notices for AI-generated content
    ssbDataNotices: {
      approximateMatch: 'Merk: Bruker nærmeste yrkeskategori ({occupation}) fra SSB',
      noDataAvailable: 'Kunne ikke finne relevant SSB-data for dette yrket',
      dataSourceCitation: 'Kilde: SSB Tabell 11418',
      usingEstimate: 'Bruker estimert data for {year}',
      occupationCodes: {
        '2223': 'Sykepleiere',
        '2512': 'Programvareutviklere',
        '2330': 'Lærere',
        '2146': 'Ingeniører (bygg og anlegg)',
      },
    },
  },

  onboarding: {
    welcomeTitle: 'Velkommen til Kjøpekraft',
    welcomeMessage:
      'Få oversikt over hva lønnen din er verdt etter prisstigningen. Sammenlign lønnsutviklingen din med prisstigningen for å se den reelle kjøpekraften.',
    loadDemoButton: 'Prøv med eksempeldata',
    addOwnDataButton: 'Legg til min egen lønn',
    whatIsKjopekraft: 'Hva er kjøpekraft?',
    kjopekraftExplanation:
      'Kjøpekraft viser hva lønnen din er verdt når prisene øker. Selv om lønnen din øker med 10 %, kan prisstigningen spise opp mye av veksten. Vi viser forskjellen mellom lønn på papiret og hva du faktisk kan kjøpe.',
    features: {
      trackSalary: {
        title: 'Spor lønnsutvikling',
        description: 'Se hvordan lønnen din endrer seg over tid.',
      },
      compareInflation: {
        title: 'Sammenlign med prisstigning',
        description: 'Forstå kjøpekraften din, ikke bare tallene.',
      },
      negotiate: {
        title: 'Forhandle smartere',
        description: 'Få innsikt som støtter lønnsforhandlinger.',
      },
    },
    demoDataInfo:
      'Dette er eksempeldata. Legg til ditt første reelle lønnspunkt for å erstatte dem.',
    clearDemoData: 'Fjern eksempeldata',
  },

  help: {
    realAnnualValue:
      'Dette viser hva startlønnen din ville vært verdt i dag, justert for prisstigning. Sammenligner kjøpekraften din nå mot da.',
    inflationAdjusted:
      'Viser hvordan lønnen din ville utviklet seg hvis den hadde fulgt prisstigningen fra starttidspunktet. Hjelper deg se om du har fått reell lønnsvekst.',
    yearlyChange:
      'Den prosentvise endringen i lønnen din fra start til nå, korrigert for prisstigning. Viser om kjøpekraften din har økt eller sunket.',
  },

  referenceSalary: {
    toggleLabel: 'Sammenlign med referanselønn',
    chartLabel: 'Referanse (Sykepleiere)',
    occupation: 'Sykepleiere',
    sourceLabel: 'Kilde: SSB',
    description: 'Median årslønn for sykepleiere (SSB)',
    enabledBadge: 'Referanse aktiv',
    helpText:
      'Sammenlign din lønnsutvikling med gjennomsnittslønn for sykepleiere i Norge basert på SSB data.',
    estimated: 'Estimert',
    official: 'Offisiell',
    estimatedNote: 'Estimert basert på SSB lønnsindeks',
  },
}
